# Generated by Django 4.2.4 on 2024-07-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_reciperecommender_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reciperecommender',
            name='cuisine_type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='reciperecommender',
            name='spice_level',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='reciperecommender',
            name='recipe',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reciperecommender',
            name='url',
            field=models.URLField(default=''),
        ),
    ]
