# Generated by Django 4.2.4 on 2024-07-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_reciperecommender_cuisine_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperecommender',
            name='user',
        ),
    ]
